//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atv1_ws
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projeto_wsEntities : DbContext
    {
        public projeto_wsEntities()
            : base("name=projeto_wsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<estados> estados { get; set; }
        public virtual DbSet<paises> paises { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<cidade> cidade { get; set; }
    }
}
