//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atv1_ws
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string dataDeNascimento { get; set; }
        public byte[] foto { get; set; }
        public string telefone { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public string cep { get; set; }
        public int id_pais { get; set; }
        public int id_estado { get; set; }
        public int id_cidade { get; set; }
        public string bairro { get; set; }
        public string endereco { get; set; }
        public bool administrador { get; set; }
    
        public virtual cidade cidade { get; set; }
        public virtual estados estados { get; set; }
        public virtual paises paises { get; set; }
    }
}
